package golden

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pmezard/go-difflib/difflib"
)

// update controls whether golden files are regenerated instead of compared.
// Pass -update on the test binary command line:
//
//	go test ./internal/golden/ -update -count=1
var update = flag.Bool("update", false, "update golden files")

// goldenDir is the path to the golden file output directory, relative to the
// test working directory (internal/golden/).
const goldenDir = "../../testdata/expected-output"

// goldenHeader returns a header comment for a golden file, documenting how
// it was generated. The comment format is compatible with both Markdown and XML.
func goldenHeader(name string) string {
	return fmt.Sprintf("<!-- Golden test file: %s\n"+
		"     Generated by: go test ./internal/golden/ -update -count=1\n"+
		"     DO NOT EDIT manually. Regenerate with the command above. -->\n", name)
}

// GoldenFile compares actual output against a golden reference file.
// When -update is set, writes actual to the golden file instead of comparing.
// Uses Normalize to strip timestamps, hashes, timing, and absolute paths
// before comparison. On mismatch, shows a unified diff.
//
// The name parameter determines the golden file path relative to the project
// root:
//
//	testdata/expected-output/<name>
//
// The dir parameter is passed to Normalize for absolute path replacement.
// If dir is empty, path normalization is skipped.
func GoldenFile(t *testing.T, name string, actual []byte, dir string) {
	t.Helper()

	golden := filepath.Join(goldenDir, name)

	// Normalize actual output.
	normalizedActual := Normalize(actual, dir)

	if *update {
		// Ensure the directory exists.
		if err := os.MkdirAll(filepath.Dir(golden), 0755); err != nil {
			t.Fatalf("golden: creating directory %s: %v", filepath.Dir(golden), err)
		}
		// Prepend a header comment documenting how this file was generated.
		header := goldenHeader(name)
		content := append([]byte(header), normalizedActual...)
		if err := os.WriteFile(golden, content, 0644); err != nil {
			t.Fatalf("golden: writing %s: %v", golden, err)
		}
		t.Logf("golden: updated %s", golden)
		return
	}

	expected, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("golden: reading %s: %v (run with -update to generate)", golden, err)
	}

	// Strip the golden header comment from expected before comparison.
	// The header is not part of the pipeline output.
	expectedStr := stripGoldenHeader(string(expected))

	// Normalize both for comparison. The stored golden file was already
	// normalized when written, but we normalize the expected output again
	// to handle any edge cases with path differences across machines.
	normalizedExpected := Normalize([]byte(expectedStr), "")

	if string(normalizedExpected) == string(normalizedActual) {
		return
	}

	// Show a unified diff on mismatch.
	diff := Diff(string(normalizedExpected), string(normalizedActual))
	t.Errorf("golden mismatch for %s:\n%s", name, diff)
}

// stripGoldenHeader removes the golden file header comment (<!-- ... -->\n)
// from the beginning of content if present.
func stripGoldenHeader(content string) string {
	if !strings.HasPrefix(content, "<!-- Golden test file:") {
		return content
	}
	idx := strings.Index(content, " -->\n")
	if idx < 0 {
		return content
	}
	return content[idx+len(" -->\n"):]
}

// Diff returns a unified diff string between expected and actual content.
// The diff uses "expected" and "actual" as file labels.
func Diff(expected, actual string) string {
	diff := difflib.UnifiedDiff{
		A:        difflib.SplitLines(expected),
		B:        difflib.SplitLines(actual),
		FromFile: "expected",
		ToFile:   "actual",
		Context:  3,
	}
	text, err := difflib.GetUnifiedDiffString(diff)
	if err != nil {
		return fmt.Sprintf("(diff error: %v)\nexpected:\n%s\nactual:\n%s", err, expected, actual)
	}
	if text == "" {
		// Fallback when diff is empty but strings differ (e.g., trailing whitespace).
		return fmt.Sprintf("outputs differ but diff is empty.\nexpected length: %d\nactual length: %d", len(expected), len(actual))
	}
	return text
}